language: generic
services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - CATKIN_LINT=pedantic
    - NOT_TEST_DOWNSTREAM=true
    - PYLINT_ARGS="--output-format=parseable --errors-only --ignored-modules=tf2_ros"
    - PYLINT2_CHECK=true
    - PYLINT3_CHECK=false
    - PARALLEL_TESTS=false
    - ROS_REPO=ros
    - VERBOSE_OUTPUT=false
    - VERBOSE_TESTS=true
  matrix:
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=melodic
install:
  - git clone --quiet --depth 1 https://github.com/fmessmer/industrial_ci.git .industrial_ci -b master_pylint
script:
  - .industrial_ci/travis.sh
