path_length:                                          # Topics for the metric 'path_length'
  topics:
    - "/tf"
    - "/scan_unified"
robot_bringup_launch: "launch/all.launch"                             # Path to the robot bringup launch file
wait_for_topics: []  # Names of the topics to wait for before beginning the test
wait_for_services: []                                 # Names of the services to wait for before beginning the test
additional_parameters:
  "/use_sim_time": true                             # Name and value of additional parameter which will be included in every recording test file
additional_arguments:                              # Name and value of additional arguments which will be included in every recording test file
  "int_res": 0.25
  "part_num": 100
