bagfile_output: "atf_recorder/data/"
test_suite_file: "atf_core/config/test_suite.yaml"
test_config_file: "atf_core/config/test_config.yaml"
robot_config_path: "cob_grasping_app/config/"

result_json_output: "atf_presenter/data/"
result_yaml_output: ""

test_application_path: "cob_grasping_app/test/grasping_app.test"
move_group_launch: "cob_grasping_app/launch/move_group.launch"
time_limit: 500.0