# single positions
hug: [[-0.0, -0.7335793379057367, 0.21923080734300773, 1.0316466675613283, 0.04120722363958612, 0.970490330571447, -1.3667847905292794]]
reverse_folded: [[-0.9599, -1.5708, 0.12, -1.0, -1.38, -0.75, 1.36]]


#lehmann
#pre_ball: [[0.20998056230743778, 0.82, -0.06997024971245268, 1.2800070201201215, -0.04000294645571004, 0.40997784129346804, -1.349994723125094]]
pre_ball: [[0.1024333737995472, 0.025429447201557383, 0.0790110552377833, 1.1543084073914898, 0.0015533430342749533, 0.6954788003347004, -1.3584944765823064]]
hold_ball: [[0.20998056230743778, 1.05, -0.06997024971245268, 1.2800070201201215, -0.04000294645571004, 0.40997784129346804, -1.349994723125094]]


#wave1: [[-1.5, 1, 0, 0, 0, 0, 0]]
wave1: [[-1.69,-1.19,0.48,2.09,0.34,-0.16,-0.12]]
#wave2: [[-1.5, 1, 0, 1, 0, 0, 0]]
wave2 : [[-1.69, -1.19, 0.48, 2.61, 0.34, 0.38, 0.5]]

carry1: [[1.3, 1, 0, 0.6, 0, 0, 0]]
carry2: [[1.3, -0.5, 0, 2, 0, 0, 0]]

point2torso: [[-1.519588366541383, -1.0853679019377138, 1.6425642656369035, 1.9734961451075483, 1.106207133206526, 1.5106697340636919, -1.7219418400176056]]
point2base: [[-1.331511686346474, -1.0853679019377138, 1.6425468123443836, 1.4519044981490428, 1.6384801951872368, 1.2950692115648323, -0.9537526230448213]]
point2head: [[-1.8957591802237208, -1.008974840577922, 1.819976984102127, 2.3907869159668724, 0.041713369122664476, 0.8099723992655284, -1.1903145498601329]]

open: [[0.4, 1.3, -1, 0.5, 0, 0, 0]]

point2camera: [[0.49, 1.04, 0.2, 1.4, 0.3, 1.5, 0]]

handover: [[-2.54, -1.0599908146137162, 1.8265568753821457, 1.4599853725857765, 1.4834251444400606, 0.7899883793301934, -2.0805720947174002]]

# far away sidewards
#pre_grasp: [[0.09403834009745447, 0.30396654252733246, 0.29567622858035936, 1.5126070495334056, -0.5322381553956708, 0.6999817498048458, 2.0]]

# in front of torso
#pre_grasp: [[-1.4999708657489668, -1.2119740858773824, 1.4699861091997042, 2.449971030902, -1.4784684093643965, -1.0791370765080939, -2.48480780277]]
#pre_grasp: [[-0.9357408251642398, -1.2479976816385454, 0.9968622555690813, 2.345652701510299, 1.0685952878260483, 1.139106589606619, -1.7841977344362432]]
pre_grasp: [[-0.5647885459453651, -1.2499873569858189, 0.5295852549326394, 2.0909917103518065, 0.540790268730443, 0.5519952825282466, -1.4522710172919617]]

retreat: [[-0.9357408251642398, -1.2479976816385454, 0.9968622555690813, 2.345652701510299, 1.0685952878260483, 1.139106589606619, -1.7841977344362432]]

# trajectory
wave_hmi: [wave1, wave2, wave1, wave2, side]
carry: [carry1, carry2, carry1]
