# example:
#   handler: ExampleParamHandler
interface:
    handler: CalculateInterfaceParamHandler
obstacle_distance:
  handler: CalculateDistanceToObstaclesParamHandler
tf_length_translation:
  handler: CalculateTfLengthTranslationParamHandler
tf_length_rotation:
  handler: CalculateTfLengthRotationParamHandler
tf_distance_translation:
  handler: CalculateTfDistanceTranslationParamHandler
tf_distance_rotation:
  handler: CalculateTfDistanceRotationParamHandler
publish_rate:
  handler: CalculatePublishRateParamHandler
resources:
  handler: CalculateResourcesParamHandler
time:
  handler: CalculateTimeParamHandler
user_result:
  handler: CalculateUserResultParamHandler
