# example:
#   handler: ExampleParamHandler
interface:
  handler: atf_metrics.calculate_interface.CalculateInterfaceParamHandler
tf_length_translation:
  handler: atf_metrics.calculate_tf_length_translation.CalculateTfLengthTranslationParamHandler
tf_length_rotation:
  handler: atf_metrics.calculate_tf_length_rotation.CalculateTfLengthRotationParamHandler
tf_distance_translation:
  handler: atf_metrics.calculate_tf_distance_translation.CalculateTfDistanceTranslationParamHandler
tf_distance_rotation:
  handler: atf_metrics.calculate_tf_distance_rotation.CalculateTfDistanceRotationParamHandler
tf_velocity_translation:
  handler: atf_metrics.calculate_tf_velocity_translation.CalculateTfVelocityTranslationParamHandler
tf_acceleration_translation:
  handler: atf_metrics.calculate_tf_acceleration_translation.CalculateTfAccelerationTranslationParamHandler
tf_jerk_translation:
  handler: atf_metrics.calculate_tf_jerk_translation.CalculateTfJerkTranslationParamHandler
publish_rate:
  handler: atf_metrics.calculate_publish_rate.CalculatePublishRateParamHandler
time:
  handler: atf_metrics.calculate_time.CalculateTimeParamHandler
user_result:
  handler: atf_metrics.calculate_user_result.CalculateUserResultParamHandler
