time:
  handler: CalculateTimeParamHandler
path_length:
  handler: CalculatePathLengthParamHandler
resources:
  handler: CalculateResourcesParamHandler
obstacle_distance:
  handler: CalculateDistanceToObstaclesParamHandler
publish_rate:
  handler: CalculatePublishRateParamHandler
interface:
    handler: CalculateInterfaceParamHandler
# example:
#   handler: ExampleParamHandler