# Definition of various test suites
testsuite_1:
  scene_config:                 # You have to define at least one scene name
    - "scene_1"
  test_config:                  # You have to define at least one test name
    - "test_1"
    - "test_2"
  robot:                        # You have to define at least one robot name
    - "robotname"
