# Definition of various test suites
testsuite_1:
  test_configs:                 # You have to define at least one test_config
    - test1
    - test2
  robots:                       # You have to define at least one robot
    - robot1
    - robot2
  robot_envs:                   # You have to define at least one robot_env
    - env1

testsuite_2:
  test_configs:                 # You have to define at least one test_config
    - test1
    - test2
  robots:                       # You have to define at least one robot
    - robot1
    - robot2
  robot_envs:                   # You have to define at least one robot_env
    - env1
