# without groundtruth, without global topics
testblock_small:
  time: []
  path_length:
    - root_frame: map
      measured_frame: base_link
#      groundtruth: 50.0 #for 230 s
#      groundtruth_epsilon: 10.0
  distance:
    - root_frame: base_link_ekf
      measured_frame: base_link 
  localization:
    - root_frame: base_link_ekf
      measured_frame: base_link 
      groundtruth: 0.0
      groundtruth_epsilon: 2.0
  resource_cpu:
    - nodes:
        -  slam
#        - ipa_loc_feature_association_node
#        - ipa_loc_feature_fusion_ekf_node
#        - ipa_loc_feature_map_server
#        - ipa_loc_feature_source_laser_node


# testblock_all empty
